services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Plenta\ContaoCountUpBundle\:
        resource: ../src
        exclude: ../src{Entity,Migrations,Resources,Tests}

    Plenta\ContaoCountUpBundle\EventListener\Contao\DataContainer\CountUpListener:
        public: true
        tags:
            - { name: 'contao.callback', table: 'tl_content', target: 'fields.plentaCountUpValue.save', method: 'onValueSaveCallback' }
            - { name: 'contao.callback', table: 'tl_content', target: 'fields.plentaCountUpValueStart.save', method: 'onValueSaveCallback' }
            - { name: 'contao.callback', table: 'tl_content', target: 'fields.plentaCountUpValue.load', method: 'onValueLoadCallback' }
            - { name: 'contao.callback', table: 'tl_content', target: 'fields.plentaCountUpValueStart.load', method: 'onValueLoadCallback' }